spring:
  application:
    name: deal
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/credit_conveyor_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  swagger-ui:
    path: /deal/swagger-ui/
server:
  port: 8081
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG