spring:
  application:
    name: conveyor

scoring:
  base-rate: 18.0
  insurance-discount: 3.0
  insurance-cost: 100000.0
  salary-client-discount: 1.0

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui