spring:
  application:
    name: conveyor

scoring:
  base-rate: 18.0
  insurance-discount: 3.0
  insurance-cost: 100000.0
  salary-client-discount: 1.0

springdoc:
  swagger-ui:
    path: /conveyor/swagger-ui/
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG